---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slot-booking
  labels:
    app.kubernetes.io/name: slot-booking
    app.kubernetes.io/instance: slot-booking-instance
    app.kubernetes.io/version: 1.16.0
spec:
  replicas: {{ .Values.slot_booking.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: slot-booking
      app.kubernetes.io/instance: slot-booking-instance
  template:
    metadata:
      annotations:
        {{ .Values.slot_booking.podAnnotations }}
      labels:
        app.kubernetes.io/name: slot-booking
        app.kubernetes.io/instance: slot-booking-instance
    spec:
      containers:
        - name: slot-booking-container
          image: {{ .Values.slot_booking.image.repository  }}
          env:
            - name: CONFIG_IMPORT
              value: {{ .Values.slot_booking.env.config_import  }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: slot-booking-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: slot-booking
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.slot_booking.service.nodePort }}
