server:
  port: ${SERVER_PORT:8081}

spring:
  # config client
  application:
    name: ${APPLICATION_NAME:slot-booking}
  profiles:
    active: ${PROFILES_ACTIVE:development}
  config:
    import: ${CONFIG_IMPORT:optional:configserver:http://localhost:8888/}
  # database h2
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: root
